In [1]:
import pandas as pd

data_answers  = pd.read_csv(r"C:\Users\camil\OneDrive\EPFL\MA4\Dataviz\Last git\data-vizards\data\handwritten_answers.csv")
data_clean = pd.read_csv(r"C:\Users\camil\OneDrive\EPFL\MA4\Dataviz\Last git\data-vizards\data\subset_df_clean.csv")

In [2]:
data_answers

,index,overall_question,specific_question,possible_answers,topic
0,Q1,How important is it in your life?,Family,"{'Very important': 1, 'Rather important': 2, '...","Social values, attitudes and stereotypes"
1,Q2,How important is it in your life?,Friends,"{'Very important': 1, 'Rather important': 2, '...","Social values, attitudes and stereotypes"
2,Q3,How important is it in your life?,Leisure time,"{'Very important': 1, 'Rather important': 2, '...","Social values, attitudes and stereotypes"
3,Q4,How important is it in your life?,Politics,"{'Very important': 1, 'Rather important': 2, '...","Social values, attitudes and stereotypes"
4,Q5,How important is it in your life?,Work,"{'Very important': 1, 'Rather important': 2, '...","Social values, attitudes and stereotypes"
5,Q6,How important is it in your life?,Religion,"{'Very important': 1, 'Rather important': 2, '...","Social values, attitudes and stereotypes"
6,Q29,"Do you \r\nstrongly agree, agree, disagree, or...","On the whole, men make better political leader...","{'Strongly agree': 1, 'Agree': 2, 'Disagree': ...","Social values, attitudes and stereotypes"
7,Q37,Do you agree or disagree with them?,It is a duty towards society to have children,"{'Strongly agree': 1, 'Agree': 2, 'Neither agr...","Social values, attitudes and stereotypes"
8,Q41,Do you agree or disagree with them?,"Work should always come first, even if it mean...","{'Strongly agree': 1, 'Agree': 2, 'Neither agr...","Social values, attitudes and stereotypes"
9,Q59,Could you tell me for each whether you trust \...,Your family,"{'Trust completely': 1, 'Trust somewhat': 2, '...","Social capital, trust and organizational membe..."
10,Q60,Could you tell me for each whether you trust \...,Your neighborhood,"{'Trust completely': 1, 'Trust somewhat': 2, '...","Social capital, trust and organizational membe..."
11,Q63,Could you tell me for each whether you trust \...,People from another nationality,"{'Trust completely': 1, 'Trust somewhat': 2, '...","Social capital, trust and organizational membe..."
12,Q75,Could you tell me how much confidence you have...,Universities,"{'A great deal': 1, 'Quite a lot': 2, 'Not ver...","Social capital, trust and organizational membe..."
13,Q90,What do you think should international organiz...,Being effective or being democratic?,"{'Being effective': 1, '2': 2, '3': 3, '4': 4,...","Social capital, trust and organizational membe..."
14,Q94,Could you tell me whether you are \r\nan activ...,Church or religious organization,"{'Active member': 2, 'Inactive member': 1, ""Do...","Social capital, trust and organizational membe..."
15,Q95,Could you tell me whether you are \r\nan activ...,"Sport or recreational organization, football/b...","{'Active member': 2, 'Inactive member': 1, ""Do...","Social capital, trust and organizational membe..."
16,Q96,Could you tell me whether you are \r\nan activ...,"Art, music or educational organization","{'Active member': 2, 'Inactive member': 1, ""Do...","Social capital, trust and organizational membe..."
17,Q97,Could you tell me whether you are \r\nan activ...,Labor Union,"{'Active member': 2, 'Inactive member': 1, ""Do...","Social capital, trust and organizational membe..."
18,Q98,Could you tell me whether you are \r\nan activ...,Political party,"{'Active member': 2, 'Inactive member': 1, ""Do...","Social capital, trust and organizational membe..."
19,Q99,Could you tell me whether you are \r\nan activ...,Environmental organization,"{'Active member': 2, 'Inactive member': 1, ""Do...","Social capital, trust and organizational membe..."
20,Q100,Could you tell me whether you are \r\nan activ...,Professional association,"{'Active member': 2, 'Inactive member': 1, ""Do...","Social capital, trust and organizational membe..."
21,Q101,Could you tell me whether you are \r\nan activ...,Humanitarian or charitable organization,"{'Active member': 2, 'Inactive member': 1, ""Do...","Social capital, trust and organizational membe..."
22,Q102,Could you tell me whether you are \r\nan activ...,Consumer Organization,"{'Active member': 2, 'Inactive member': 1, ""Do...","Social capital, trust and organizational membe..."
23,Q103,Could you tell me whether you are \r\nan activ...,"Self-help group, mutual aid group","{'Active member': 2, 'Inactive member': 1, ""Do...","Social capital, trust and organizational membe..."
24,Q104,Could you tell me whether you are \r\nan activ...,Women's group,"{'Active member': 2, 'Inactive member': 1, ""Do...","Social capital, trust and organizational membe..."
25,Q159,Read the statement and say how much you agree ...,"Because of science and technology, there will...","{'Completely disagree': 1, '2': 2, '3': 3, '4'...","Social values, attitudes and stereotypes"
26,Q160,Read the statement and say how much you agree ...,We depend too much on science and not enough o...,"{'Completely disagree': 1, '2': 2, '3': 3, '4'...","Social values, attitudes and stereotypes"
27,Q178,Can the following actions be justified?,Avoiding a fare on public transport,"{'Never justifiable': 1, '2': 2, '3': 3, '4': ...",Ethical values and norms
28,Q182,Can the following actions be justified?,Homosexuality,"{'Never justifiable': 1, '2': 2, '3': 3, '4': ...",Ethical values and norms
29,Q184,Can the following actions be justified?,Abortion,"{'Never justifiable': 1, '2': 2, '3': 3, '4': ...",Ethical values and norms
30,Q185,Can the following actions be justified?,Divorce,"{'Never justifiable': 1, '2': 2, '3': 3, '4': ...",Ethical values and norms
31,Q186,Can the following actions be justified?,Sex before marriage,"{'Never justifiable': 1, '2': 2, '3': 3, '4': ...",Ethical values and norms
32,Q187,Can the following actions be justified?,Suicide,"{'Never justifiable': 1, '2': 2, '3': 3, '4': ...",Ethical values and norms
33,Q188,Can the following actions be justified?,Euthanasia,"{'Never justifiable': 1, '2': 2, '3': 3, '4': ...",Ethical values and norms
34,Q189,Can the following actions be justified?,For a man to beat his wife,"{'Never justifiable': 1, '2': 2, '3': 3, '4': ...",Ethical values and norms
35,Q195,Can the following actions be justified?,Death penalty,"{'Never justifiable': 1, '2': 2, '3': 3, '4': ...",Ethical values and norms
36,Q196,Should the government have the right to...,Keep people under video surveillance in public...,"{'Definitely should have the right': 1, 'Proba...",Ethical values and norms
37,Q197,Should the government have the right to...,Monitor all e-mails and Internet info exchange,"{'Definitely should have the right': 1, 'Proba...",Ethical values and norms
38,Q260,Demographic,Sex,"{'Male': 1, 'Female': 2}",Demographics
39,Q262,Demographic,Age,Numerical age,Demographics
40,Q275,Demographic,Education,"{'No education': 0, 'Primary education' : 1,'L...",Demographics
41,Q287,Demographic,Economic class,"{'Upper class': 1, 'Upper middle class': 2, 'L...",Demographics
42,Q289,Demographic,Religion,"{ 'No': 0, 'Roman Catholic': 1, 'Protestant':...",Demographics
43,Q290,Demographic,Ethnic group,"{ 'White': 1, 'Black': 2, 'South Asian Indian,...",Demographics

In [20]:
questions_of_interest = [
    "How important is family?",
    "How important are friends?",
    "How important is leisure time?",
    "How important is politics?",
    "How important is work?",
    "How important is religion?",
    "Men make better political leaders than women – agree?",
    "Having children is a duty to society – agree?",
    "Work should come before free time – agree?",
    "Trust in your family?",
    "Trust in your neighborhood?",
    "Trust in other nationalities?",
    "Confidence in universities?",
    "Should global orgs prioritize effectiveness or democracy?"
]

In [24]:
questions_of_interest_values = data_answers['index'].iloc[0:len(questions_of_interest)+1].tolist()

question_dict = dict(zip(questions_of_interest, questions_of_interest_values))
print(question_dict)

{'How important is family?': 'Q1', 'How important are friends?': 'Q2', 'How important is leisure time?': 'Q3', 'How important is politics?': 'Q4', 'How important is work?': 'Q5', 'How important is religion?': 'Q6', 'Men make better political leaders than women – agree?': 'Q29', 'Having children is a duty to society – agree?': 'Q37', 'Work should come before free time – agree?': 'Q41', 'Trust in your family?': 'Q59', 'Trust in your neighborhood?': 'Q60', 'Trust in other nationalities?': 'Q63', 'Confidence in universities?': 'Q75', 'Should global orgs prioritize effectiveness or democracy?': 'Q90'}

In [14]:
data_answers['questions_to_explore'] = data_answers['overall_question'] + data_answers['specific_question']
data_answers['questions_to_explore'].tolist()

['How important is it in your life?Family',
 'How important is it in your life?Friends',
 'How important is it in your life?Leisure time',
 'How important is it in your life?Politics',
 'How important is it in your life?Work',
 'How important is it in your life?Religion',
 'Do you \r\nstrongly agree, agree, disagree, or strongly disagree?On the whole, men make better political leaders than women do ',
 ' Do you agree or disagree with them?It is a duty towards society to have children ',
 ' Do you agree or disagree with them?Work should always come first, even if it means less spare \r\ntime ',
 'Could you tell me for each whether you trust \r\npeople from this group completely, somewhat, not very much or not at all?Your family',
 'Could you tell me for each whether you trust \r\npeople from this group completely, somewhat, not very much or not at all?Your neighborhood',
 'Could you tell me for each whether you trust \r\npeople from this group completely, somewhat, not very much or not at all?People from another nationality',
 'Could you tell me how much confidence you have in \r\nthem: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all? Universities',
 'What do you think should international organizations prioritize? Being effective or being democratic?',
 'Could you tell me whether you are \r\nan active member, an inactive member or not a member of that type of organization?Church or religious organization',
 'Could you tell me whether you are \r\nan active member, an inactive member or not a member of that type of organization?Sport or recreational organization, football/baseball/rugby team',
 'Could you tell me whether you are \r\nan active member, an inactive member or not a member of that type of organization?Art, music or educational organization',
 'Could you tell me whether you are \r\nan active member, an inactive member or not a member of that type of organization?Labor Union',
 'Could you tell me whether you are \r\nan active member, an inactive member or not a member of that type of organization?Political party',
 'Could you tell me whether you are \r\nan active member, an inactive member or not a member of that type of organization?Environmental organization',
 'Could you tell me whether you are \r\nan active member, an inactive member or not a member of that type of organization?Professional association',
 'Could you tell me whether you are \r\nan active member, an inactive member or not a member of that type of organization?Humanitarian or charitable organization',
 'Could you tell me whether you are \r\nan active member, an inactive member or not a member of that type of organization?Consumer Organization',
 'Could you tell me whether you are \r\nan active member, an inactive member or not a member of that type of organization?Self-help group, mutual aid group',
 "Could you tell me whether you are \r\nan active member, an inactive member or not a member of that type of organization?Women's group",
 'Read the statement and say how much you agree or disagree with it. Because of science and technology, there will be more opportunities for the next generation. ',
 'Read the statement and say how much you agree or disagree with it.We depend too much on science and not enough on faith.',
 'Can the following actions be justified?Avoiding a fare on public transport',
 'Can the following actions be justified?Homosexuality',
 'Can the following actions be justified?Abortion',
 'Can the following actions be justified?Divorce',
 'Can the following actions be justified?Sex before marriage',
 'Can the following actions be justified?Suicide',
 'Can the following actions be justified?Euthanasia',
 'Can the following actions be justified?For a man to beat his wife',
 'Can the following actions be justified?Death penalty',
 'Should the government have the right to...Keep people under video surveillance in public areas',
 'Should the government have the right to...Monitor all e-mails and Internet info exchange',
 'DemographicSex',
 'DemographicAge',
 'DemographicEducation',
 'DemographicEconomic class',
 'DemographicReligion',
 'DemographicEthnic group']

In [3]:
data_clean[['Q29','Q260', 'Q262', 'Q287', 'Q289']]

       Q29  Q260  Q262  Q287  Q289
0        3     2    60     3     1
1        3     1    47     2     1
2        3     1    48     3     1
3        4     2    62     4     0
4        3     1    49     4     0
...    ...   ...   ...   ...   ...
97215    1     2    43     3     1
97216    1     1    34     2     2
97217    3     2    22     4     1
97218    3     2    48     4     1
97219    3     1    38     4     1

[97220 rows x 5 columns]

=> Faire une liste de toutes lse questions pour les histogrames
=> Faire qu'on puisse séléctionner un pays
=> Enlever tt les participants du pays qui ont pas d'infos valides sur les questions + genre ext...
=> Map les réponses qui ont une range de 10 en 1-3, 4-6, 7-10
=> Faire un dict data par catégorie 
    dict_data = {Gender: [
      {
        attribute: "Male",
        values: [
          { range: 'Yo', value: 5 },
          { range: '4-6', value: 10 },
          { range: '7-10', value: 15 }
        ]
      },
      {
        attribute: "Female",
        values: [
          { range: 'Yo', value: 3 },
          { range: '4-6', value: 6 },
          { range: '7-10', value: 9 }
        ]
      }
    ],
    Age: [
      {
        attribute: "Group1",
        values: [
          { range: '1-3', value: 8 },
          { range: '4-6', value: 12 },
          { range: '7-10', value: 6 }
        ]
      },
      {
        attribute: "Group2",
        values: [
          { range: '1-3', value: 7 },
          { range: '4-6', value: 5 },
          { range: '7-10', value: 13 }
        ]
      }
    ]}

In [7]:
import numpy as np
selected_question = 'Q29'
data_clean_valid = data_clean[data_clean[[selected_question, 'Q260', 'Q287']] > 0]
data_clean_valid = data_clean_valid[['Q260',selected_question,'Q287']] #.groupby('Q260').mean().reset_index()
answers_per_gender = data_clean_valid.groupby(['Q260', selected_question]).count().reset_index() 
answers_per_gender['Q287'] /= answers_per_gender['Q287'].sum() / 100
answers_per_gender['Q287'] =answers_per_gender['Q287'].round(4)
answers_per_gender.columns = ['Gender', 'Question', 'Answers']

answers_per_gender

   Gender  Question  Answers
0     1.0       1.0   8.6597
1     1.0       2.0  13.6213
2     1.0       3.0  18.5248
3     1.0       4.0   6.9722
4     2.0       1.0   6.4075
5     2.0       2.0  12.3588
6     2.0       3.0  21.6525
7     2.0       4.0  11.8031

In [31]:
def map_range(val):
    if 1 <= val <= 3:
        return '1-3'
    elif 4 <= val <= 6:
        return '4-6'
    elif 7 <= val <= 10:
        return '7-10'

In [57]:
def clean_for_histograms(data_clean, selected_country, selected_question, Gender_idx = 'Q260', Age_idx = 'Q287', Religion_idx ='Q289', Ethnic_idx = 'Q290' ):
    
    # Selects only valid answers
    data_clean = data_clean[data_clean[[selected_question, Gender_idx, Age_idx, Religion_idx, Ethnic_idx]] > 0]

    if data_clean.shape[0] == 10:
        data_clean[selected_question] = data_clean[selected_question].apply(map_range)

    
    data_gender = data_clean[Gender_idx]



    return data_gender, data_age, data_religion

In [ ]:
clean_for_histograms(data_clean, 'AFG', '')

TypeError: clean_for_histograms() missing 1 required positional argument: 'selected_question'